place = ['xizang','guangdong','zhejiang','riben','haerbin']
print(place)
print(sorted(place))
print(sorted(place,reverse = True))
print(place)
place.reverse()
print(place)
place.reverse()
print(place)
place.sort()
print(place)
place.sort(reverse=True)
print(place)
print(place.reverse())